feat: Add authentication service
courselab/pollex pull request #16
Opened 2022-10-06 15:08 UTC by natanbc

Fixes #10

2022-10-07 10:59 UTC, FulecoRafa requested changes

2022-10-07 10:59 UTC, FulecoRafa commented on auth/Makefile
> +TEST_SERVICE_KEY=5up3r53cur3p4ssw0rd
Essas chaves de segurança podem subir para o github?

2022-10-07 10:59 UTC, FulecoRafa commented on auth/Makefile
> +auth: main.go auth.go
Interessante colocar duas regras: uma que é essa, para build e deploy e uma para desenvolvimento utilizando o comando `go run`

2022-10-07 10:59 UTC, FulecoRafa commented on auth/auth.go
> +func NewAuth(key [keySize]byte) (*Auth, error) {
**Opcional**: Segundo as boas práticas de Go, essa função deveria se chamar `MakeAuth`

2022-10-07 10:59 UTC, FulecoRafa commented on auth/main.go
> +        bodyReader := http.MaxBytesReader(w, r.Body, 65536)
Embora o limite realmente seja grande, isso não poderia trazer problemas se a mensagem for muito grande?

2022-10-07 10:59 UTC, FulecoRafa commented on auth/main.go
> +        var req TokenPayload
**Pergunta**: Aqui o conteúdo do `token` vai vir junto no campo, correto?

2022-10-07 11:00 UTC, FulecoRafa commented
Should relate to an issue. Does it not exist? Then we should create it

2022-10-25 16:45 UTC, natanbc commented on auth/main.go
> +        var req TokenPayload
Sim, `{"token": "..."}` no body do request.

2022-10-25 16:46 UTC, natanbc commented on auth/main.go
> +        bodyReader := http.MaxBytesReader(w, r.Body, 65536)
O token é pra ser pequeno, até porque muitas implementações limitam o tamanho de valores pra headers HTTP

2022-10-25 17:28 UTC, FulecoRafa approved these changes

2022-10-25 17:29 UTC, FulecoRafa commented
LGTM

2022-10-25 17:31 UTC, merged