Create link.txt
courselab/pollex pull request #26
Opened 2022-11-23 14:12 UTC by marcelats

prototype of the application

2022-11-23 16:11 UTC, FulecoRafa requested changes
Mudaria o nome do arquivo para ficar mais explicativo, mas fora isso, tudo certo!

2022-11-23 16:18 UTC, marcelats commented
alterado o nome do arquivo

2022-11-23 17:09 UTC, FulecoRafa approved these changes

2022-11-23 17:09 UTC, FulecoRafa commented
Troca para a branch de dev por favor

2022-11-23 19:27 UTC, marcelats commented
criada nova pull request

2022-11-24 16:57 UTC, FulecoRafa commented
Criado novo PR para branch correta

2022-11-24 16:57 UTC, closed without merging